[package]
name = "maki-workcell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
maki-agent = { workspace = true }
maki-storage = { workspace = true }
async-trait = { workspace = true }
futures-lite = { workspace = true }
flume = { workspace = true }
jiff = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
workcell = { workspace = true }

[dev-dependencies]
maki-config = { workspace = true }
smol = { workspace = true }
tempfile = { workspace = true }
