[package]
name = "workcell-mcp-files"
description = "Typed confined and host-managed filesystem tools for Workcell"
readme = "README.md"
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
index = [
  "dep:tree-sitter",
  "dep:workcell-source-languages",
]
mcp = ["dep:rmcp"]

[dependencies]
dunce.workspace = true
file-format.workspace = true
notify-8.workspace = true
regex = { workspace = true, default-features = true }
rustix-038.workspace = true
rmcp = { workspace = true, optional = true }
schemars.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
sha2 = { workspace = true, default-features = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros"] }
tokio-util.workspace = true
tree-sitter = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4"] }
workcell-source-languages = { workspace = true, optional = true }
workcell-tool-contract.workspace = true
workcell-host-contract.workspace = true

[target.'cfg(windows)'.dependencies]
winapi-util.workspace = true
windows-sys.workspace = true

[dev-dependencies]
proptest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
