[package]
name = "caudra-decision"
description = "Runtime-neutral TypeSafe System One decision contracts and client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-io = { workspace = true }
async-trait = { workspace = true }
fastrand = { workspace = true }
futures-lite = { workspace = true }
isahc = { workspace = true }
jiff = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
