[package]
name = "caudra-storage"
description = "Persistent sessions, credentials, and state for Caudra."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
caudra-workspace = { workspace = true }
flume = { workspace = true }
getrandom = { workspace = true }
isahc = { workspace = true }
jiff = { workspace = true }
memchr = { workspace = true }
regex = { workspace = true }
regex-automata = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
rusqlite = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
etcetera = { workspace = true }
bs58 = { workspace = true }
uuid = { workspace = true }
zstd = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
tempfile = { workspace = true }
isahc = { workspace = true }
serde_json = { workspace = true }
criterion = { workspace = true }
flate2 = { workspace = true }

[[bench]]
name = "payload_codecs"
harness = false
